-- a)
CREATE TABLE See (
	SeeNr INTEGER NOT NULL PRIMARY KEY,
	Name TEXT NOT NULL,
	Laenge REAL NOT NULL,
	Breite REAL NOT NULL
);

-- b)
ALTER TABLE See ADD COLUMN Tiefe INTEGER;

-- c)
ALTER TABLE See DROP COLUMN Tiefe;
ALTER TABLE See ADD COLUMN Tiefe REAL;

-- d)
ALTER TABLE See DROP COLUMN Tiefe;

-- e)
DROP TABLE See;